version: '3.1'

services:
  mongo: 
    image: mongo
    container_name: mongo
    env_file:
      - .mongo.env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - mongodata:/data/db
    command: mongod --auth
    
volumes:
  mongodata: